spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqut?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 112520ki
#将mybatis的mapper.xml注册进来
mybatis:
  mapper-locations: "mapper/*Mapper.xml"