spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqut?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 112520ki
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
#      password: 123456
#将mybatis的mapper.xml注册进来
mybatis:
  mapper-locations: "mapper/*Mapper.xml"
server:
  port: 8081

logging:
  level:
    cn.itsource.mapper: debug